import java.util.Objects;

public class Student implements Observer {

    private String name;

    public Student(String name){
        this.name=name;
    }

    public String getName(){
        return this.name;
    }

    @Override
    public boolean equals(Object o) {   //autogenerated
        if (this == o) return true;
        if (!(o instanceof Student)) return false;
        Student student = (Student) o;
        return getName().equals(student.getName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getName());
    }

    public void listenTo(Teacher teacher){
        teacher.register(this);
    }

    @Override
    public void update(String message) {
        System.out.println("Student "+ this.name+ " learned about "+ message);
    }
}
